### ISSUE TITLE
Rebase to v1.10.18 versions of vdb geth

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-pg-ipfs-state-snapshot#37]
Child of https://github.com/vulcanize/go-ethereum/issues/231

- [x] v3 release that uses the new v1.10.18-statediff-3.2.1 release of vdb geth (off of https://github.com/vulcanize/ipld-eth-state-snapshot/tree/release-v3.0.2)
- [x] v4 release that uses the new v1.10.18-statediff-4.0.1-alpha release of vdb geth (off of https://github.com/vulcanize/ipld-eth-state-snapshot/tree/release-v4.0.2-alpha)

This will also potentially involve updating the dependency on go-eth-state-node-iterator to the version resultant of https://github.com/vulcanize/go-eth-state-node-iterator/issues/12

**Comment by abdulrabbani00** [comment]
Final:
* v3 - https://github.com/vulcanize/ipld-eth-state-snapshot/releases/tag/v3.0.3
* v4 - Coming soon
